version: '3.3'

services:

  web:
    build: .
    env_file:
      - ./.env
    stop_signal: SIGINT
    container_name: web
    volumes:
      - ./dump/app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge